-- MySQL Script generated by MySQL Workbench
-- 08/05/22 14:25:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto_biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_biblioteca` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `projeto_biblioteca` ;

-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`usuario` (
  `rm` INT NOT NULL COMMENT '',
  `nome` VARCHAR(60) NULL COMMENT '',
  `email` VARCHAR(120) NULL COMMENT '',
  `dt_nascimento` DATE NULL COMMENT '',
  `genero` CHAR(1) NULL COMMENT '',
  `telefone` VARCHAR(45) NULL COMMENT '',
  `senha` CHAR(20) NULL COMMENT '',
  `perfil` VARCHAR(120) NULL COMMENT '',
  `status` VARCHAR(100) NULL COMMENT '',
  `obs` VARCHAR(200) NULL COMMENT '',
  `adm` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`rm`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`genero` (
  `cd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`cd`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`editora` (
  `cd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(80) NULL COMMENT '',
  PRIMARY KEY (`cd`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`livro` (
  `cd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `isbn` VARCHAR(100) NULL COMMENT '',
  `titulo` VARCHAR(200) NULL COMMENT '',
  `ano` INT(4) NULL COMMENT '',
  `qtd` INT NULL COMMENT '',
  `sinopse` LONGTEXT NULL COMMENT '',
  `capa` VARCHAR(200) NULL COMMENT '',
  `classificacao` VARCHAR(45) NULL COMMENT '',
  `id_editora` INT NOT NULL COMMENT '',
  `id_genero` INT NOT NULL COMMENT '',
  `estado` LONGTEXT NULL COMMENT '',
  PRIMARY KEY (`cd`, `id_editora`, `id_genero`)  COMMENT '',
  INDEX `fk_livro_editora1_idx` (`id_editora` ASC)  COMMENT '',
  INDEX `fk_livro_genero1_idx` (`id_genero` ASC)  COMMENT '',
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`id_editora`)
    REFERENCES `projeto_biblioteca`.`editora` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_genero1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `projeto_biblioteca`.`genero` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`autor` (
  `cd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(60) NULL COMMENT '',
  PRIMARY KEY (`cd`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`autor_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`autor_livro` (
  `id_livro` INT NOT NULL COMMENT '',
  `id_autor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_livro`, `id_autor`)  COMMENT '',
  INDEX `fk_livro_has_autor_autor1_idx` (`id_autor` ASC)  COMMENT '',
  INDEX `fk_livro_has_autor_livro_idx` (`id_livro` ASC)  COMMENT '',
  CONSTRAINT `fk_livro_has_autor_livro`
    FOREIGN KEY (`id_livro`)
    REFERENCES `projeto_biblioteca`.`livro` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `projeto_biblioteca`.`autor` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`emprestimo` (
  `id_usuario` INT NOT NULL COMMENT '',
  `id_livro` INT NOT NULL COMMENT '',
  `dt_emprestimo` DATE NULL COMMENT '',
  `dt_devolucao` DATE NULL COMMENT '',
  `status` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id_usuario`, `id_livro`)  COMMENT '',
  INDEX `fk_usuario_has_livro_livro1_idx` (`id_livro` ASC)  COMMENT '',
  INDEX `fk_usuario_has_livro_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_has_livro_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projeto_biblioteca`.`usuario` (`rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_livro_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `projeto_biblioteca`.`livro` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`livro_emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`livro_emprestimo` (
  `id_emprestimo` INT NOT NULL COMMENT '',
  `id_livro` INT NOT NULL COMMENT '',
  `nota` INT(1) NULL COMMENT '',
  PRIMARY KEY (`id_emprestimo`, `id_livro`)  COMMENT '',
  INDEX `fk_emprestimo_has_livro_livro1_idx` (`id_livro` ASC)  COMMENT '',
  INDEX `fk_emprestimo_has_livro_emprestimo1_idx` (`id_emprestimo` ASC)  COMMENT '',
  CONSTRAINT `fk_emprestimo_has_livro_emprestimo1`
    FOREIGN KEY (`id_emprestimo`)
    REFERENCES `projeto_biblioteca`.`emprestimo` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_has_livro_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `projeto_biblioteca`.`livro` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`favorito` (
  `cd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `id_livro` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cd`, `id_usuario`, `id_livro`)  COMMENT '',
  INDEX `fk_favorito_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_favorito_livro1_idx` (`id_livro` ASC)  COMMENT '',
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projeto_biblioteca`.`usuario` (`rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `projeto_biblioteca`.`livro` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_biblioteca`.`fila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_biblioteca`.`fila` (
  `cd` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_livro` INT NOT NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cd`, `id_livro`, `id_usuario`)  COMMENT '',
  INDEX `fk_fila_livro1_idx` (`id_livro` ASC)  COMMENT '',
  INDEX `fk_fila_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_fila_livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `projeto_biblioteca`.`livro` (`cd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fila_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projeto_biblioteca`.`usuario` (`rm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
